
controller:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
    repository: boxboat/dockhand-secrets-operator
    tag: v0.4.1
  resources: {}

webhook:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
    repository: boxboat/dockhand-secrets-operator
    tag: v0.4.1
  resources: {}
