
# set allowCrossNamespace to true for single tenant cross namespace Profile reference
# see https://secrets-operator.dockhand.dev/usage/core-concepts/
allowCrossNamespace: false

controller:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
    repository: boxboat/dockhand-secrets-operator
    tag: v1.1.0
  resources: {}

webhook:
  replicas: 1
  image:
    pullPolicy: IfNotPresent
    repository: boxboat/dockhand-secrets-operator
    tag: v1.1.0
  resources: {}
