---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dockhand-lru-registry.name" . }}-conf
  labels:
    {{- include "dockhand-lru-registry.labels" . | nindent 4 }}
data:
  registry-config.yaml: |
    {{ (tpl (.Files.Get "files/conf/registry-config.yaml") .) | nindent 4 }}
