name: Main

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: azure/setup-helm@v1
        id: install

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        if: ${{ steps.version.outputs.PUBLISH == 'yes' }}
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Package Helm Charts
        run: |
          helm package *
          mkdir dockhand-charts
          mv *.tgz dockhand-charts/
          gsutil cp gs://dockhand-charts/index.yaml ./dockhand-charts/
          helm repo index dockhand-charts --merge ./dockhand-charts/index.yaml --url https://dockhand-charts.storage.googleapis.com

      - name: Publish
        run: |
          cd ./dockhand-charts;
          gsutil -m -q cp * gs://dockhand-charts/
